# Generated by Django 5.2.3 on 2025-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('co2', models.FloatField()),
                ('humo', models.FloatField()),
                ('temperatura', models.FloatField()),
            ],
        ),
    ]
